name: Calculator Pipeline

  on:
    push:

  jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: "3.12"

        - name: Install dependencies
          run: pip install flake8 pytest pytest-cov

        - name: Run flake8
          working-directory: kurs-testning-python/ovningar/05
          run: flake8 calculator.py calculator_test.py --max-line-length=120

        - name: Run pytest with coverage
          working-directory: kurs-testning-python/ovningar/05
          run: pytest -v --cov=calculator --cov-report=term-missing --cov-branch --cov-fail-
  under=80 calculator_test.py